// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBtLlCFmSY58t6O7pw01LzoQurFc42vj0A',
//     appId: '1:795804681706:web:958c43437ab8bf2908de93',
//     messagingSenderId: '795804681706',
//     projectId: 'bmihealth-malaysi',
//     authDomain: 'bmihealth-malaysi.firebaseapp.com',
//     storageBucket: 'bmihealth-malaysi.appspot.com',
//     measurementId: 'G-WDHWDJXW7Q',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBMGVLpamB23EPweNLWEIMlWQGjXrQ4HXQ',
//     appId: '1:795804681706:android:a1b6bdc25551cbe908de93',
//     messagingSenderId: '795804681706',
//     projectId: 'bmihealth-malaysi',
//     storageBucket: 'bmihealth-malaysi.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD7A60M6htPF0Qe9czdrvxkTN-6m-q12hg',
//     appId: '1:795804681706:ios:d8a2bba47853688608de93',
//     messagingSenderId: '795804681706',
//     projectId: 'bmihealth-malaysi',
//     storageBucket: 'bmihealth-malaysi.appspot.com',
//     iosClientId: '795804681706-dlogd6gu8mc2seiliirt7jcjsov9mf49.apps.googleusercontent.com',
//     iosBundleId: 'com.mjd.bmihealthMalaysia',
//   );
// }
